# Generated by Django 3.2.8 on 2024-10-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemTrade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='state',
            field=models.IntegerField(choices=[(0, '撤销'), (1, '初始化'), (2, '购买'), (3, '出售'), (4, '拒绝'), (5, '完成'), (6, '已出货')], default=1),
        ),
    ]
