# Generated by Django 3.2.8 on 2024-11-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemTrade', '0002_alter_trade_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewforitem',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reviewfortrade',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
