# Generated by Django 3.2.8 on 2024-10-08 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemTrade', '0005_alter_itemimage_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='itemTrade.item'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='state',
            field=models.CharField(choices=[('Code_0', '撤销'), ('Code_1', '初始化'), ('Code_2', '购买'), ('Code_3', '出售'), ('Code_4', '拒绝'), ('Code_5', '完成'), ('Code_6', '已出货')], default='Code_1', max_length=50),
        ),
    ]
